monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.*"
      }
    ]
    actions = {
      update-props = {
        api.alsa.split-enable = false
      }
    }
  }
  {
    matches = [
      {
        device.name = "alsa_card.pci-0000_01_00.1"
      }
      {
        alsa.card_name = "HDA NVidia"
      }
    ]
    actions = {
      update-props = {
        api.alsa.use-acp = false
      }
    }
  }
]
