# konfigurasi terminal kitty phantomshell (tema persona 5 phantom crimson)
# ubah font_size atau background_opacity di bawah kalau mau gedein font atau transparansi terminal

font_family                 JetBrains Mono NF
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
font_size                   11.0

window_padding_width        14
background_opacity          0.92
confirm_os_window_close     0
cursor_shape                beam
cursor_trail                3

# palet warna persona 5 phantom crimson
foreground                  #FFFFFF
background                  #0B0B0E
selection_foreground        #0B0B0E
selection_background        #E60012
cursor                      #E60012
cursor_text_color           #FFFFFF

# Black
color0                      #141419
color8                      #454556

# Red (Phantom Crimson)
color1                      #E60012
color9                      #FF1E2E

# Green (Metaverse Emerald)
color2                      #00F59B
color10                     #52FFBA

# Yellow (Star Gold)
color3                      #FFD700
color11                     #FFE853

# Blue (Velvet Blue)
color4                      #00B4D8
color12                     #48CAE4

# Magenta
color5                      #FF0055
color13                     #FF4D88

# Cyan
color6                      #00F0FF
color14                     #70F8FF

# White
color7                      #E5E5F0
color15                     #FFFFFF
