import QtQuick

// kumpulan preset palet warna persona dan daftar wallpaper bawaan
QtObject {
    id: root

    readonly property string defaultWallpaperPath: "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper.png"

    readonly property var availableWallpapers: [
        "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper.png",
        "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-p3-reload.png",
        "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-p4-golden.png",
        "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-kasumi-violet.png",
        "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-akechi-crow.png",
        "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-futaba-matrix.png",
        "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-monochrome.png",
        "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-expressive.png",
        "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-tonal-spot.png",
        "/home/sho/Pictures/Wallpapers/goremagala_iceshard.jpg",
        "/home/sho/Pictures/Wallpapers/1409986.png",
        "/home/sho/Pictures/Wallpapers/wallhaven-0q3yqq.jpg",
        "/home/sho/Pictures/Wallpapers/wallhaven-28z766.png",
        "/home/sho/Pictures/Wallpapers/wallhaven-6d9o96.png",
        "/home/sho/Pictures/Wallpapers/wallhaven-72m78v.png",
        "/home/sho/Pictures/Wallpapers/wallhaven-l3g222.png",
        "/home/sho/Pictures/Wallpapers/wallhaven-j3vvdw.png"
    ]

    readonly property var presets: ({
        "p5-crimson": {
            name: "P5 Phantom Crimson",
            id: "p5-crimson",
            wallpaper: "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper.png",
            primary: "#E60012",
            secondary: "#FFD700",
            accent: "#FF1E2E",
            background: "#0B0B0E",
            surface: "#141419",
            surfaceAlt: "#1F1F27",
            foreground: "#FFFFFF",
            muted: "#9E9EAE",
            borderLight: "#FFFFFF",
            borderDark: "#000000",
            urgent: "#FF0033",
            success: "#00F59B"
        },
        "p3-reload": {
            name: "P3 Reload S.E.E.S. Blue",
            id: "p3-reload",
            wallpaper: "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-p3-reload.png",
            primary: "#00B4D8",
            secondary: "#90E0EF",
            accent: "#00F0FF",
            background: "#070C18",
            surface: "#0E172C",
            surfaceAlt: "#182544",
            foreground: "#F8FBFF",
            muted: "#8DA4C4",
            borderLight: "#E0F7FF",
            borderDark: "#040811",
            urgent: "#FF2A6D",
            success: "#05FFA1"
        },
        "p4-golden": {
            name: "P4 Golden Midnight",
            id: "p4-golden",
            wallpaper: "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-p4-golden.png",
            primary: "#FFB703",
            secondary: "#FB8500",
            accent: "#FFE600",
            background: "#100F0C",
            surface: "#1C1A14",
            surfaceAlt: "#2B271E",
            foreground: "#FFFDF7",
            muted: "#B5AC96",
            borderLight: "#FFF5D6",
            borderDark: "#080705",
            urgent: "#E63946",
            success: "#52B788"
        },
        "kasumi-violet": {
            name: "Violet Kasumi",
            id: "kasumi-violet",
            wallpaper: "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-kasumi-violet.png",
            primary: "#B829FF",
            secondary: "#FF70A6",
            accent: "#D96BFF",
            background: "#0C0812",
            surface: "#171122",
            surfaceAlt: "#231934",
            foreground: "#FDF8FF",
            muted: "#A899B8",
            borderLight: "#F5E6FF",
            borderDark: "#06030A",
            urgent: "#FF2A85",
            success: "#00F5D4"
        },
        "akechi-crow": {
            name: "Crow Royal Gold",
            id: "akechi-crow",
            wallpaper: "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-akechi-crow.png",
            primary: "#D4AF37",
            secondary: "#E60012",
            accent: "#FFF3B0",
            background: "#0A0A0C",
            surface: "#151519",
            surfaceAlt: "#222228",
            foreground: "#FAFAFC",
            muted: "#9E9EA8",
            borderLight: "#FFF8DC",
            borderDark: "#050507",
            urgent: "#E60012",
            success: "#52B788"
        },
        "futaba-matrix": {
            name: "Oracle Hacker Matrix",
            id: "futaba-matrix",
            wallpaper: "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-futaba-matrix.png",
            primary: "#39FF14",
            secondary: "#FF9F1C",
            accent: "#72FF57",
            background: "#060C08",
            surface: "#0E1912",
            surfaceAlt: "#16281D",
            foreground: "#F0FFF4",
            muted: "#84A98C",
            borderLight: "#D8F3DC",
            borderDark: "#030704",
            urgent: "#FF595E",
            success: "#39FF14"
        },
        "monochrome": {
            name: "Phantom Monochrome",
            id: "monochrome",
            wallpaper: "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-monochrome.png",
            primary: "#E2E2EC",
            secondary: "#A0A0B2",
            accent: "#FFFFFF",
            background: "#09090B",
            surface: "#141418",
            surfaceAlt: "#202026",
            foreground: "#FFFFFF",
            muted: "#8E8E9E",
            borderLight: "#FFFFFF",
            borderDark: "#000000",
            urgent: "#FF4D6D",
            success: "#80ED99"
        },
        "expressive": {
            name: "Velvet Expressive",
            id: "expressive",
            wallpaper: "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-expressive.png",
            primary: "#7B61FF",
            secondary: "#00F5D4",
            accent: "#9D85FF",
            background: "#0B0B14",
            surface: "#141526",
            surfaceAlt: "#1F2138",
            foreground: "#F8F8FF",
            muted: "#9A9CB8",
            borderLight: "#E8E8FF",
            borderDark: "#06060C",
            urgent: "#FF3366",
            success: "#00F5D4"
        },
        "tonal-spot": {
            name: "Gore Magala Ice",
            id: "tonal-spot",
            wallpaper: "/mnt/data/Projects/rice/phantomshell/dots/quickshell/assets/pshell-wallpaper-tonal-spot.png",
            primary: "#8AB4F8",
            secondary: "#C58AF9",
            accent: "#A8C7FA",
            background: "#0A0C12",
            surface: "#131722",
            surfaceAlt: "#1D2232",
            foreground: "#F2F6FC",
            muted: "#94A0B8",
            borderLight: "#E2ECFF",
            borderDark: "#05060A",
            urgent: "#F28B82",
            success: "#81C995"
        }
    })
}
